services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: communere_rag:${COMMUNERERAG_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      chroma:
        condition: service_started
    environment:
      COMMUNERERAG_HOST: 0.0.0.0
      COMMUNERERAG_DB_HOST: CommunereRAG-db
      COMMUNERERAG_DB_PORT: 27017
      COMMUNERERAG_DB_USER: CommunereRAG
      COMMUNERERAG_DB_PASS: CommunereRAG
      COMMUNERERAG_DB_BASE: admin
      COMMUNERERAG_REDIS_HOST: CommunereRAG-redis
  db:
    image: mongo:7.0
    hostname: CommunereRAG-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "CommunereRAG"
      MONGO_INITDB_ROOT_PASSWORD: "CommunereRAG"
    command: "mongod"
    volumes:
      - CommunereRAG-db-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 40

  taskiq-worker:
    <<: *main_app
    labels: [ ]
    command:
      - taskiq
      - worker
      - CommunereRAG.tkq:broker

  chroma:
    image: chromadb/chroma:latest
    volumes:
      - index_data:/chroma_storage
#    environment:
#      - CHROMA_DB_IMPL=duckdb+parquet
#      - CHROMA_PERSIST_DIRECTORY=/chroma_storage

  redis:
    image: bitnami/redis:6.2.5
    hostname: "CommunereRAG-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50
volumes:
  CommunereRAG-db-data:
    name: CommunereRAG-db-data
  index_data:
